name = "TripletEmbeddings"
uuid = "942c5cd0-cd18-11e9-2366-6d016c645f9f"
authors = ["Karel Mundnich <mundnich@usc.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
